cookie:
  expiry_days: 30
  key: supersecretkeychatbot0123456789
  name: chatbot_auth

# Google OAuth Settings
google_oauth:
  enabled: true
  allowed_domain: "gmail.com" 
  admin_google_users:
    - soumyadoshi28@gmail.com # Put your personal Gmail here to test SSO admin rights

# Traditional Login Credentials 
credentials:
  usernames:
    soham:
      name: "Soumya Doshi"
      email: "soumyadoshi28@example.com"
      # The password below is hashed. The plaintext password to log in is: admin123
      password: "scrypt:32768:8:1$k0hKj0iLw3tT2B9R$0d5b7a1f5999824f11467615bc5e59b2d8e036e864c2cf9b17355030e4dbdfb8"